### ISSUE TITLE
The keyword "extend" is lost

### ISSUE THREAD

**Issue by kaihaase-wd** [nicolasdao/graphql-s2s#1]
If the keyword `extend` is used in the schema (see [Extending Types of graphql-tools](http://dev.apollodata.com/tools/graphql-tools/generate-schema.html#extend-types)), it is lost after using the function `transpileSchema`.

**Comment by nicolasdao** [comment]
Hi @kaihaase-wd ,

Thanks for finding that issue. I'll try to fix this asap. I'll let you know when this is fixed. 

Cheers,

Nic

**Comment by nicolasdao** [comment]
Hi @kaihaase-wd ,

I've just pushed a fixed. Can you please install the latest version from npm (0.3.1) and let me know if that fixes your problem?

**Comment by kaihaase-wd** [comment]
Hello @nicolasdao,

thank you very much! 

In version 0.3.1 the problem has been fixed and as of version 0.3.2 it is now also possible to use 'scalar'.
