### ISSUE TITLE
Why is this library not more successful 

### ISSUE THREAD

**Issue by FredericLatour** [nicolasdao/graphql-s2s#11]
I'm somewhat new to Graphql and the problems solved by this library seem like problems one should be facing rather sooner than later when building schema definitions.

Therefore, what could be the reason that this library is not more successful?

* People do not like to deviate from the official schema definition? (in case the library is not updated in the future)
* Is there an alternative approach to achieve the same thing ?
* Maybe the Graphql schema definition will soon include those features?

I just want to be sure that I'm not going into a dead end.

**Comment by nicolasdao** [comment]
Hi @FredericLatour ,

Well, first and foremost, thank you for your compliment. I spent a decent amount of time building and documenting this project, so I'm glad you seem to appreciate the problems it tackles. Now to answer your question:
1. I have no clue what people do or do not like. I think that when they have a problem to fix, they find a way to fix it. Ideally, that way is standard. By the way, graphql-s2s is just a transpiler. The result is an entirely standard GraphQL schema.
2. As far as I'm concerned, there is no alternative to my library.
3. I'm not sure what's the roadmap of graphql.js.

Other details that might help:
1. GraphQL is still pretty new. Best practices are slowly emerging, and more and more people are exploring better ways to code GraphQL servers. I hope this library can establish some best practice, and who knows, maybe one day have some of its concepts integrated into the official graphql.js (not to myself, submit a pull request to graphql.js).
2. My team and I have created a consultancy in Sydney called Neap. We build mobile & web apps and consequently GraphQL API. We're maintaining this library, and as long as we're doing this for a living, we'll keep supporting it with all upcoming version of graphql.js. 
3. I haven't promoted this library very well yet. I've just started a new series on Medium called The [GraphQL Series](https://blog.neap.co/the-graphql-series-graphql-schemas-on-steroid-16679d7d4941). Maybe that will increase the adoption. In the end, I think that if you start seeing more stars (there are 41 as I'm writing this answer), then you and I will have more peace of mind that the problems this lib are solving are legit :).

I use this lib in production on a daily basis for my clients, and so far I'm pretty happy with what it does. As you can see, a few people have reported bugs. I'm trying to fix them as soon as they are reported. 

Hope this helps to answer your worries.

Thanks again for your message.

Cheers,

Nic

**Comment by FredericLatour** [comment]
Hi,
Thanks for taking the time to provide such a detailed answer.
I have now digged deeper into graphql and that's indeed a fast moving area. I'm starting to understand why people would not necessarily use your library even though it provides much needed features:

* Some people will generate their schema automatically (be it from their database, their ORM model, a generic schema vocabulary, etc ..;
* some people will want to use Typescript to define their schema (even though I'm a typescript guy, I believe graphql typescript, definition are quite ugly and I prefer generating typescript interfaces from gql schemas instead).
* Some people prefer duplicating definition in order to have more self descriptive less abastract types (which I don't agree with ... they are tons of tools to generate a documentation or to navigate type definition. An easier maintenance is way more important to me)
* Some people will want to define their schema in a .graphql file with intellisense support (which **Unfortunately** I don't think will be possible when using the language extensions provided by your transpiler), ... the most important limitation from my point of view.

Therefore, the best solution would be that your language extension are included in the Gql Schema Definition language.  You should propose your approach. that's a very neat approach.

**Comment by nicolasdao** [comment]
Great analysis @FredericLatour . I didn't think about TypeScript as I don't use it. That's an extremely valid point. 

I forgot to mention that you can definitely define your schema using .graphql files. Graphql-s2s will work just fine. BTW, I've also created another open-source project called [schemaglue.js](https://github.com/nicolasdao/schemaglue) that helps to break down your schema into many .graphql files. I've written an article about that one called [GraphQL Schemas — Easier & Better Structure](https://hackernoon.com/graphql-schemas-easier-better-structure-31677a640d18). 

Thanks a lot for responding to my previous answer. This really helps me to think forward.

Cheers,

Nic

**Comment by Toub** [comment]
Note that features that make graphql schema more concise, such as inheritance, are not compatible with graphql designers current vision: https://github.com/facebook/graphql/issues/335

I agree that tooling is probably the most significant issue to make this library more successful.

@see https://github.com/nicolasdao/graphql-s2s/issues/30

**Comment by nicolasdao** [comment]
Hi @Toub,

First and foremost, happy new year. Thanks a lot for your interest and support for our graphql-s2s library. Your thoughts about tooling make a lot of sense. We'd love to have more contributors helping us with tooling. If you feel like helping our community to make a difference, your contribution will be highly appreciated. 

Thanks again for the great feedback.

We wish you all the best for this epic new year.

Nic and the rest of the team.
