### ISSUE TITLE
Leading comment causes transpilation error

### ISSUE THREAD

**Issue by tmcnab** [nicolasdao/graphql-s2s#15]
The leading comment in this type definition:

```gql
    # The most generic type of item. See also: schema.org/Thing
    type Thing {
        description: String
        identifier: ID!
        name: String
        url: String
    }

    # A person (alive, dead, undead, or fictional). See also: schema.org/Person
    type Person inherits Thing {
        email: String
        familyName: String
        givenName: String
    }
```

Causes the following error:
```
Error: Schema error: type Person cannot find inherited type Thing
    at /<path>/node_modules/graphql-s2s/src/graphqls2s.js:447:10
```

However if the leading comment is omitted ("`# The most generic type of item. See also: schema.org/Thing`") then transpilation works correctly.

**Comment by nicolasdao** [comment]
Hi @tmcnab ,

Thanks for catching that one. I'll fix this issue ASAP.

Cheers,

Nic

**Comment by Larinel** [comment]
@nicolasdao  I think it caused by comment containing word `type`. After removed this word, everything works good
