### ISSUE TITLE
Keyword scalar lost

### ISSUE THREAD

**Issue by rafaelnsantos** [nicolasdao/graphql-s2s#2]
If the keyword scalar is used in the schema [(see Custom scalars)](https://www.apollographql.com/docs/graphql-tools/scalars.html#Date-as-a-scalar), it is lost after using the function transpileSchema.

**Comment by nicolasdao** [comment]
Thanks for finding that issue @rafaelnsantos . I'll fix this ASAP and I'll buzz you when that's done.

**Comment by nicolasdao** [comment]
Hi @rafaelnsantos,

Sorry for the delay. This is now fixed. I've also added support for the [union](https://medium.com/the-graphqlhub/graphql-tour-interfaces-and-unions-7dd5be35de0d) keyword.

Just update to the latest version (0.3.2) and you should be all good to go.

Let me know how that goes or if there is anything else you think that could be made better.

Cheers,

Nic
