### ISSUE TITLE
Missing support for 'descriptions'

### ISSUE THREAD

**Issue by jimmed** [nicolasdao/graphql-s2s#29]
Fairly recently, the GraphQL spec was extended to add the concept of ['descriptions'][descriptions] ─ essentially comments describing types and fields.

For example (lifted from the spec):

```graphql
"""
A simple GraphQL schema which is well described.
"""
type Query {
  """
  Translates a string from a given language into a different language.
  """
  translate(
    "The original language that `text` is provided in."
    fromLanguage: Language

    "The translated language to be returned."
    toLanguage: Language

    "The text to be translated."
    text: String
  ): String
}
```

Unfortunately, graphql-s2s cannot parse this new syntax; the following error is thrown at startup:

```
TypeError: Cannot read property 'match' of undefined
    at genTypes.forEach.genType ([...]/node_modules/graphql-s2s/src/graphqls2s.js:286:43)
```

I'll take a look at fixing this myself and raising a PR, but I can't promise anything! Finally, thanks for creating such a useful library!

[descriptions]: https://facebook.github.io/graphql/draft/#sec-Descriptions

**Comment by nicolasdao** [comment]
Hi @jimmed ,

Thanks heaps for reporting this. This issue has already been reported by @yostools in https://github.com/nicolasdao/graphql-s2s/issues/17. 

I'll try to fix this asap.

Really appreciate your support.

Nic

**Comment by luisfrocha** [comment]
Any updates on this? Was a PR ever submitted? I ran into this issue today. Not a big deal, as we're not really using the descriptions, but it would be nice to be able to start adding them.

**Comment by nicolasdao** [comment]
Hi @luisfrocha, 

I haven't had time to fix that issue yet. I can't give you an ETA yet as I'm quite busy at the moment, but I'll try to fix asap.

Thanks for helping the community.

Cheers,

Nic

**Comment by phoenix741** [comment]
Hi,

I create a pull request to add the support of descriptions.
If you don't have time to develop it, can you review the code i wrote ?

Thanks

**Comment by nicolasdao** [comment]
Big thanks to @phoenix741 for fixing this issue. The latest release (0.19.1) on npm contains that PR. I'm closing this issue now. Thanks all for your support.
