### ISSUE TITLE
duplicate property 

### ISSUE THREAD

**Issue by yasintz** [nicolasdao/graphql-s2s#33]
![Screenshot_8](https://user-images.githubusercontent.com/36041339/54065424-04edc480-4232-11e9-9730-d6348d95a5fe.png)
can you prevent this from happening ?
it shouldn't be too hard

**Comment by nicolasdao** [comment]
Hi @yasintz,

Can you provide the schema before it is transpiled to see how to recreate this error? 

I've seen your PR. That seems great, so thank you so much for jumping in. Our community development guidelines require that you also provide the unit test. Add that to you PR and I'll gladly finish your PR review before merging it to master.

To add a unit test, follow the explanations described in the README here: https://github.com/nicolasdao/graphql-s2s#contribute

In your case, you'll add your unit test under:
```js
describe('graphqls2s', () =>
    describe('#transpileSchema', () => {
      ...
      it('26 - FIX: Should not duplicate properties', () => {
            Your unit test here
      })
    })
```

Thanks a lot for reporting that issue @yasintz as well as jumping in to fix it.

Cheers,

Nic

**Comment by yasintz** [comment]
i updated my pr. Thanks for this library. it works exactly

**Comment by yasintz** [comment]
Why not use typescrip ?

**Comment by yasintz** [comment]
it's so hard to understand. Why don't you file the components ?
