### ISSUE TITLE
character } in directives breaks transpiling

### ISSUE THREAD

**Issue by kraney** [nicolasdao/graphql-s2s#37]
For example
```
type Mutation {
      CreateArea(name: String): Area @cypher(statement: "CREATE (a:Area {name: $name, creationDate: timestamp()}) RETURN a")
}
```

The regex matches on the curly brace inside the quotes and parens, so it loses the last part of the definition.

**Comment by cambeme** [comment]
I faced this problem today too, any solution?

**Comment by nicolasdao** [comment]
Hi @kraney and @cambeme,

Thanks heaps for reporting this. I've opened a ticket. We'll look into this asap.

**Comment by nicolasdao** [comment]
Hi @kraney and @cambeme,

I've just pushed a fix for that issue (get the latest npm version 0.20.2). 

Let me know if this works for you now.

Cheers,

Nic
