### ISSUE TITLE
support for .graphql files

### ISSUE THREAD

**Issue by anuragnagarkota** [nicolasdao/graphql-s2s#6]
Hi there !
Thanks for the wonderful stuff. Could you support .graphql files to write shcemas.

Thanks

**Comment by nicolasdao** [comment]
Interesting @anuragnagarkota. Let me see what I can do. I should be able to come back to you within 48 hours.

**Comment by anuragnagarkota** [comment]
Thanks @nicolasdao

**Comment by nicolasdao** [comment]
Hi @anuragnagarkota ,

Sorry for the delay. I've just released a new major version of schemaglue, and I'm very happy to announce that .graphql files are now the defacto file extension to breakdown GraphQl schemas. 

Please have a look at the latest documentation and let me know your thoughts.

Thanks for your awesome support.

Nic

**Comment by anuragnagarkota** [comment]
It worked @nicolasdao . Thanks a lot!

**Comment by nzhtrtlc** [comment]
I still have error Unexpected Name "inherits" in my .graphql file :/

**Comment by nicolasdao** [comment]
Hi @nzhtrtlc,

Can you share your code and provide some more context? That would help diagnose your issue.
