### ISSUE TITLE
How do you plan to keep up with latest graphql-js library?

### ISSUE THREAD

**Issue by rohitghatol** [nicolasdao/graphql-s2s#9]
Hi,
I love this library but one of the thing that concerns me is how we have to copy the language folder from graphql-js library. I see we have done that 3 months back which I understand why you had to do.  Now the language folder of latest graphql-js library has changed.

My concern is how do we keep up with latest graphql-js language changes?

If you have some thoughts on this please share , may be the community may be able to help out with pull requests.

Again appreciate awesome work done here and looking forward to be educated on the question raised in this issue.

Cheers
Rohit

**Comment by nicolasdao** [comment]
Hi  @rohitghatol,

Following your feedback, I've removed the explicit reference to the language folder and replaced it with adding an explicit dependency to graphql.js.

Thanks a lot for pointing that out.

Cheers,

Nic
